### ISSUE TITLE
Error while starting rails app with this gem: undefined method 'sign_in' for class DeviseController

### ISSUE THREAD

**Issue by hrigu** [ValiMail/devise-secure_password#31]
Hi,
I get an error when I start my rails app with this gem:
`=> Booting Thin`
`=> Rails 5.0.6 application starting in development on http://0.0.0.0:3000`
`=> Run `rails server -h` for more startup options `
 `Exiting`
 `Uncaught exception: undefined method `sign_in' for class `DeviseController'`
 `Process finished with exit code 0`

I'm using 
- Ruby 2.5.1
- Rails 5.1
- devise 4.4.3
- devise-secure_password 1.1.0

It's the line `alias devise_sign_in sign_in` in the File [devise_helper.rb](https://github.com/ValiMail/devise-secure_password/blob/master/lib/devise/secure_password/controllers/devise_helpers.rb)

When I comment out the alias line, I can start the app, but, of course the login process won't work: "no method devise_sign_in"

The same error happens when I run the generator task `rails generate devise:secure_password:install`

**Comment by kotlyarenko-d** [comment]
I have the same error

- devise 4.7.1
- devise-secure_password 1.1.0
- rails 5.1.7
- ruby 2.5.3

**Comment by eliascaceresy** [comment]
I have the same error, any solution?

ruby 2.5.3
rails 5.2
devise 4.7.1
devise-secure_password 1.1.0

**Comment by mirandashort-bark** [comment]
Same error

ruby 2.5.7
rails 5.2.4.4
devise 4.7.1
devise-secure_password 1.1.8

**Comment by geeksam** [comment]
The original is over four years and several Ruby & Rails versions old.  The most recent comment dates from not quite two years before my start date at Valimail.

Please feel free to reopen if encountered again.  _(Fair warning, though:  this gem doesn't get a lot of attention internally, so you may still be on your own.  Frankly, I don't think this gem offers much public value; you might be better off forking or just DIY.)_
