### ISSUE TITLE
No release supports Rails 6 with Ruby 2.6

### ISSUE THREAD

**Issue by kieraneglin** [ValiMail/devise-secure_password#73]
We have an app running on Ruby 2.6 that was recently upgraded to the latest version of Rails 6.  Version 1.1.0 of this Gem doesn't support Railties >= 6 whereas version 2.0.0 doesn't support Ruby < 2.7.

It doesn't appear that this Gem uses any Ruby 2.7-exclusive methods.  Would you be open to a PR that adds support for Ruby 2.6?

**Comment by geeksam** [comment]
When this issue was opened, Ruby 2.6 was less than three months from EOL [[source](https://endoflife.date/ruby)].  As I write this, Ruby 3.1 is the lowest version still receiving updates.
