### ISSUE TITLE
Please cut a release for Rails 7 support

### ISSUE THREAD

**Issue by dorner** [ValiMail/devise-secure_password#82]
The updated gemspec has been merged, but there is no new version, meaning this gem cannot be used with Rails 7. Would really appreciate a version bump!

**Comment by cesarjr** [comment]
Hi @dorner ! 

Are you using this gem at Rails 7? Are you using it from master? How did (or if) you solve your problem? 

I'm using it at Rails 6 and I'd like to upgrade my project to Rails 7. This is the only gem that railsbump.org is reporting that still does not support Rails 7 in my project.

Thanks.

**Comment by dorner** [comment]
We ended up removing this gem and just using a validation on the User model directly.

**Comment by cesarjr** [comment]
😥 

I'm gonna wait more some time and maybe do the same.

thanks! 🤜🤛

**Comment by prostko** [comment]
Hello!

Bumping this issue.

Looks like everything is all set, only task remaining is to cut a new release for Rails 7 support.

**Comment by vokshirg** [comment]
Hey! also interested in upgrade

**Comment by geeksam** [comment]
Hey, all.  The original authors and maintainers of this gem left the company, and the work to maintain it hasn't been prioritized.  I'm hoping to be able to release a new version soon, for an unknown value of "soon" 😬

**Comment by geeksam** [comment]
Apropos of nothing in particular, I would just like to mention that Rails' `ActiveModel::Validations` has a lot of very nice features, without any additional layers of `devise` magic.

In light of the recent `xz` vulnerability, this seems like a good time for reevaluating third-party dependencies in general.  🙃

**Comment by geeksam** [comment]
https://rubygems.org/gems/devise-secure_password/versions/2.1.0
